# Generated by Django 4.2.3 on 2023-07-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Men Shirts'), ('MB', 'Mobiles'), ('ES', 'Electronics'), ('SP', 'Sports'), ('PC', 'Personal Care'), ('AP', 'Home Appliances')], max_length=2),
        ),
    ]
