# Generated by Django 4.2.3 on 2023-08-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile_num',
            new_name='mobile',
        ),
    ]
