# Generated by Django 4.2.3 on 2023-08-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
    ]
